### ISSUE TITLE
Help needed | the TLDR mod causes crash when mc starts

### ISSUE THREAD

**Issue by Boxedbox1976** [kkllffaa/meteor-utils#7]
paste from log
======================================================================================
14:37:28.623
FabricLoader/Mixin
main
Error loading class: net/minecraft/world/chunk/WorldChunk (java.lang.ClassNotFoundException: net/minecraft/world/chunk/WorldChunk)
14:37:28.624
FabricLoader
main
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.systems.modules.world.StashFinder failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.systems.modules.world.StashFinder failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_128.handler$zoi000$onAddStackTrace(class_128.java:524)
	at net.minecraft.class_128.method_555(class_128.java:78)
	at net.minecraft.class_128.method_568(class_128.java:132)
	at net.minecraft.class_128.method_24305(class_128.java:272)
	at net.minecraft.client.main.Main.main(Main.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:102)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for meteor-utils.mixins.json:StashFinderMixin during activity: [Transform -> Method debil(Lmeteordevelopment/meteorclient/events/world/ChunkDataEvent;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKEVIRTUAL -> net/minecraft/world/chunk/WorldChunk::getPos:()Lnet/minecraft/util/math/ChunkPos;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.world.chunk.WorldChunk
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 25 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.WorldChunk
	... 29 more
14:37:28.942
monitor
Process Monitor
Process crashed with exit code 1
======================================================================================

**Comment by kkllffaa** [comment]
use normal version without dev in name
